name: Meticulous

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  meticulous-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: npm start &
        env:
          CI: false
          BROWSER: none

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000 --timeout 120000

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action/cloud-compute@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: http://localhost:3000
